#define GPIO_CONF_IN_ANALOG   0x00000000
#define GPIO_CONF_IN_FLOAT    0x00000001
#define GPIO_CONF_IN_PU_PD    0x00000002
#define GPIO_CONF_IN_RSVD     0x00000003
#define GPIO_CONF_GPIO_OUT_PP 0x00000000
#define GPIO_CONF_GPIO_OUT_OD 0x00000001
#define GPIO_CONF_ALT_OUT_PP  0x00000002
#define GPIO_CONF_ALT_OUT_OD  0x00000003

#define GPIO_MODE_IN          0x00000000
#define GPIO_MODE_OUT_10MHz   0x00000001
#define GPIO_MODE_OUT_2MHz    0x00000002
#define GPIO_MODE_OUT_50MHz   0x00000003

// user configurable part starts here

// GPIOA CONFIG and MODE settings
#define GPIOA_P00_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P00_MODE GPIO_MODE_IN

#define GPIOA_P01_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P01_MODE GPIO_MODE_IN

#define GPIOA_P02_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P02_MODE GPIO_MODE_IN

#define GPIOA_P03_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P03_MODE GPIO_MODE_IN

#define GPIOA_P04_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P04_MODE GPIO_MODE_IN

#define GPIOA_P05_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P05_MODE GPIO_MODE_IN

#define GPIOA_P06_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P06_MODE GPIO_MODE_IN

#define GPIOA_P07_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P07_MODE GPIO_MODE_IN

#define GPIOA_P08_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P08_MODE GPIO_MODE_IN

#define GPIOA_P09_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P09_MODE GPIO_MODE_IN

#define GPIOA_P10_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P10_MODE GPIO_MODE_IN

#define GPIOA_P11_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P11_MODE GPIO_MODE_IN

#define GPIOA_P12_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P12_MODE GPIO_MODE_IN

#define GPIOA_P13_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P13_MODE GPIO_MODE_IN

#define GPIOA_P14_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P14_MODE GPIO_MODE_IN

#define GPIOA_P15_CONF GPIO_CONF_IN_FLOAT
#define GPIOA_P15_MODE GPIO_MODE_IN

// GPIOB CONFIG and MODE settings
#define GPIOB_P00_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P00_MODE GPIO_MODE_IN

#define GPIOB_P01_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P01_MODE GPIO_MODE_IN

#define GPIOB_P02_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P02_MODE GPIO_MODE_IN

#define GPIOB_P03_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P03_MODE GPIO_MODE_IN

#define GPIOB_P04_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P04_MODE GPIO_MODE_IN

#define GPIOB_P05_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P05_MODE GPIO_MODE_IN

#define GPIOB_P06_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P06_MODE GPIO_MODE_IN

#define GPIOB_P07_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P07_MODE GPIO_MODE_IN

#define GPIOB_P08_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P08_MODE GPIO_MODE_IN

#define GPIOB_P09_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P09_MODE GPIO_MODE_IN

#define GPIOB_P10_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P10_MODE GPIO_MODE_IN

#define GPIOB_P11_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P11_MODE GPIO_MODE_IN

#define GPIOB_P12_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P12_MODE GPIO_MODE_IN

#define GPIOB_P13_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P13_MODE GPIO_MODE_IN

#define GPIOB_P14_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P14_MODE GPIO_MODE_IN

#define GPIOB_P15_CONF GPIO_CONF_IN_FLOAT
#define GPIOB_P15_MODE GPIO_MODE_IN

// GPIOC CONFIG and MODE settings
#define GPIOC_P00_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P00_MODE GPIO_MODE_IN

#define GPIOC_P01_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P01_MODE GPIO_MODE_IN

#define GPIOC_P02_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P02_MODE GPIO_MODE_IN

#define GPIOC_P03_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P03_MODE GPIO_MODE_IN

#define GPIOC_P04_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P04_MODE GPIO_MODE_IN

#define GPIOC_P05_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P05_MODE GPIO_MODE_IN

#define GPIOC_P06_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P06_MODE GPIO_MODE_IN

#define GPIOC_P07_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P07_MODE GPIO_MODE_IN

#define GPIOC_P08_CONF GPIO_CONF_GPIO_OUT_PP
#define GPIOC_P08_MODE GPIO_MODE_OUT_10MHz

#define GPIOC_P09_CONF GPIO_CONF_GPIO_OUT_PP
#define GPIOC_P09_MODE GPIO_MODE_OUT_10MHz

#define GPIOC_P10_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P10_MODE GPIO_MODE_IN

#define GPIOC_P11_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P11_MODE GPIO_MODE_IN

#define GPIOC_P12_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P12_MODE GPIO_MODE_IN

#define GPIOC_P13_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P13_MODE GPIO_MODE_IN

#define GPIOC_P14_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P14_MODE GPIO_MODE_IN

#define GPIOC_P15_CONF GPIO_CONF_IN_FLOAT
#define GPIOC_P15_MODE GPIO_MODE_IN

// GPIOD CONFIG and MODE settings
#define GPIOD_P00_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P00_MODE GPIO_MODE_IN

#define GPIOD_P01_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P01_MODE GPIO_MODE_IN

#define GPIOD_P02_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P02_MODE GPIO_MODE_IN

#define GPIOD_P03_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P03_MODE GPIO_MODE_IN

#define GPIOD_P04_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P04_MODE GPIO_MODE_IN

#define GPIOD_P05_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P05_MODE GPIO_MODE_IN

#define GPIOD_P06_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P06_MODE GPIO_MODE_IN

#define GPIOD_P07_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P07_MODE GPIO_MODE_IN

#define GPIOD_P08_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P08_MODE GPIO_MODE_IN

#define GPIOD_P09_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P09_MODE GPIO_MODE_IN

#define GPIOD_P10_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P10_MODE GPIO_MODE_IN

#define GPIOD_P11_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P11_MODE GPIO_MODE_IN

#define GPIOD_P12_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P12_MODE GPIO_MODE_IN

#define GPIOD_P13_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P13_MODE GPIO_MODE_IN

#define GPIOD_P14_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P14_MODE GPIO_MODE_IN

#define GPIOD_P15_CONF GPIO_CONF_IN_FLOAT
#define GPIOD_P15_MODE GPIO_MODE_IN

// GPIOE CONFIG and MODE settings
#define GPIOE_P00_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P00_MODE GPIO_MODE_IN

#define GPIOE_P01_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P01_MODE GPIO_MODE_IN

#define GPIOE_P02_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P02_MODE GPIO_MODE_IN

#define GPIOE_P03_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P03_MODE GPIO_MODE_IN

#define GPIOE_P04_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P04_MODE GPIO_MODE_IN

#define GPIOE_P05_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P05_MODE GPIO_MODE_IN

#define GPIOE_P06_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P06_MODE GPIO_MODE_IN

#define GPIOE_P07_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P07_MODE GPIO_MODE_IN

#define GPIOE_P08_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P08_MODE GPIO_MODE_IN

#define GPIOE_P09_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P09_MODE GPIO_MODE_IN

#define GPIOE_P10_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P10_MODE GPIO_MODE_IN

#define GPIOE_P11_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P11_MODE GPIO_MODE_IN

#define GPIOE_P12_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P12_MODE GPIO_MODE_IN

#define GPIOE_P13_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P13_MODE GPIO_MODE_IN

#define GPIOE_P14_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P14_MODE GPIO_MODE_IN

#define GPIOE_P15_CONF GPIO_CONF_IN_FLOAT
#define GPIOE_P15_MODE GPIO_MODE_IN

// user configurable part ends here

// GPIO A
#define GPIOA_CRL (GPIOA_P07_CONF << 30) | (GPIOA_P07_MODE << 28) | \
                  (GPIOA_P06_CONF << 26) | (GPIOA_P06_MODE << 24) | \
                  (GPIOA_P05_CONF << 22) | (GPIOA_P05_MODE << 20) | \
                  (GPIOA_P04_CONF << 18) | (GPIOA_P04_MODE << 16) | \
                  (GPIOA_P03_CONF << 14) | (GPIOA_P03_MODE << 12) | \
                  (GPIOA_P02_CONF << 10) | (GPIOA_P02_MODE << 8) | \
                  (GPIOA_P01_CONF << 6) | (GPIOA_P01_MODE << 4) | \
                  (GPIOA_P00_CONF << 2) | (GPIOA_P00_MODE << 0)
#define GPIOA_CRH (GPIOA_P15_CONF << 30) | (GPIOA_P15_MODE << 28) | \
                  (GPIOA_P14_CONF << 26) | (GPIOA_P14_MODE << 24) | \
                  (GPIOA_P13_CONF << 22) | (GPIOA_P13_MODE << 20) | \
                  (GPIOA_P12_CONF << 18) | (GPIOA_P12_MODE << 16) | \
                  (GPIOA_P11_CONF << 14) | (GPIOA_P11_MODE << 12) | \
                  (GPIOA_P10_CONF << 10) | (GPIOA_P10_MODE << 8) | \
                  (GPIOA_P09_CONF << 6) | (GPIOA_P09_MODE << 4) | \
                  (GPIOA_P08_CONF << 2) | (GPIOA_P08_MODE << 0)

// GPIO B
#define GPIOB_CRL (GPIOB_P07_CONF << 30) | (GPIOB_P07_MODE << 28) | \
                  (GPIOB_P06_CONF << 26) | (GPIOB_P06_MODE << 24) | \
                  (GPIOB_P05_CONF << 22) | (GPIOB_P05_MODE << 20) | \
                  (GPIOB_P04_CONF << 18) | (GPIOB_P04_MODE << 16) | \
                  (GPIOB_P03_CONF << 14) | (GPIOB_P03_MODE << 12) | \
                  (GPIOB_P02_CONF << 10) | (GPIOB_P02_MODE << 8) | \
                  (GPIOB_P01_CONF << 6) | (GPIOB_P01_MODE << 4) | \
                  (GPIOB_P00_CONF << 2) | (GPIOB_P00_MODE << 0)
#define GPIOB_CRH (GPIOB_P15_CONF << 30) | (GPIOB_P15_MODE << 28) | \
                  (GPIOB_P14_CONF << 26) | (GPIOB_P14_MODE << 24) | \
                  (GPIOB_P13_CONF << 22) | (GPIOB_P13_MODE << 20) | \
                  (GPIOB_P12_CONF << 18) | (GPIOB_P12_MODE << 16) | \
                  (GPIOB_P11_CONF << 14) | (GPIOB_P11_MODE << 12) | \
                  (GPIOB_P10_CONF << 10) | (GPIOB_P10_MODE << 8) | \
                  (GPIOB_P09_CONF << 6) | (GPIOB_P09_MODE << 4) | \
                  (GPIOB_P08_CONF << 2) | (GPIOB_P08_MODE << 0)

// GPIO C
#define GPIOC_CRL ((GPIOC_P07_CONF << 30) | (GPIOC_P07_MODE << 28) | \
                   (GPIOC_P06_CONF << 26) | (GPIOC_P06_MODE << 24) | \
                   (GPIOC_P05_CONF << 22) | (GPIOC_P05_MODE << 20) | \
                   (GPIOC_P04_CONF << 18) | (GPIOC_P04_MODE << 16) | \
                   (GPIOC_P03_CONF << 14) | (GPIOC_P03_MODE << 12) | \
                   (GPIOC_P02_CONF << 10) | (GPIOC_P02_MODE << 8) | \
                   (GPIOC_P01_CONF << 6) | (GPIOC_P01_MODE << 4) | \
                   (GPIOC_P00_CONF << 2) | (GPIOC_P00_MODE << 0))
#define GPIOC_CRH ((GPIOC_P15_CONF << 30) | (GPIOC_P15_MODE << 28) | \
                   (GPIOC_P14_CONF << 26) | (GPIOC_P14_MODE << 24) | \
                   (GPIOC_P13_CONF << 22) | (GPIOC_P13_MODE << 20) | \
                   (GPIOC_P12_CONF << 18) | (GPIOC_P12_MODE << 16) | \
                   (GPIOC_P11_CONF << 14) | (GPIOC_P11_MODE << 12) | \
                   (GPIOC_P10_CONF << 10) | (GPIOC_P10_MODE << 8) | \
                   (GPIOC_P09_CONF << 6) | (GPIOC_P09_MODE << 4) | \
                   (GPIOC_P08_CONF << 2) | (GPIOC_P08_MODE << 0))

// GPIO D
#define GPIOD_CRL (GPIOD_P07_CONF << 30) | (GPIOD_P07_MODE << 28) | \
                  (GPIOD_P06_CONF << 26) | (GPIOD_P06_MODE << 24) | \
                  (GPIOD_P05_CONF << 22) | (GPIOD_P05_MODE << 20) | \
                  (GPIOD_P04_CONF << 18) | (GPIOD_P04_MODE << 16) | \
                  (GPIOD_P03_CONF << 14) | (GPIOD_P03_MODE << 12) | \
                  (GPIOD_P02_CONF << 10) | (GPIOD_P02_MODE << 8) | \
                  (GPIOD_P01_CONF << 6) | (GPIOD_P01_MODE << 4) | \
                  (GPIOD_P00_CONF << 2) | (GPIOD_P00_MODE << 0)
#define GPIOD_CRH (GPIOD_P15_CONF << 30) | (GPIOD_P15_MODE << 28) | \
                  (GPIOD_P14_CONF << 26) | (GPIOD_P14_MODE << 24) | \
                  (GPIOD_P13_CONF << 22) | (GPIOD_P13_MODE << 20) | \
                  (GPIOD_P12_CONF << 18) | (GPIOD_P12_MODE << 16) | \
                  (GPIOD_P11_CONF << 14) | (GPIOD_P11_MODE << 12) | \
                  (GPIOD_P10_CONF << 10) | (GPIOD_P10_MODE << 8) | \
                  (GPIOD_P09_CONF << 6) | (GPIOD_P09_MODE << 4) | \
                  (GPIOD_P08_CONF << 2) | (GPIOD_P08_MODE << 0)

// GPIO E
#define GPIOE_CRL (GPIOE_P07_CONF << 30) | (GPIOE_P07_MODE << 28) | \
                  (GPIOE_P06_CONF << 26) | (GPIOE_P06_MODE << 24) | \
                  (GPIOE_P05_CONF << 22) | (GPIOE_P05_MODE << 20) | \
                  (GPIOE_P04_CONF << 18) | (GPIOE_P04_MODE << 16) | \
                  (GPIOE_P03_CONF << 14) | (GPIOE_P03_MODE << 12) | \
                  (GPIOE_P02_CONF << 10) | (GPIOE_P02_MODE << 8) | \
                  (GPIOE_P01_CONF << 6) | (GPIOE_P01_MODE << 4) | \
                  (GPIOE_P00_CONF << 2) | (GPIOE_P00_MODE << 0)
#define GPIOE_CRH (GPIOE_P15_CONF << 30) | (GPIOE_P15_MODE << 28) | \
                  (GPIOE_P14_CONF << 26) | (GPIOE_P14_MODE << 24) | \
                  (GPIOE_P13_CONF << 22) | (GPIOE_P13_MODE << 20) | \
                  (GPIOE_P12_CONF << 18) | (GPIOE_P12_MODE << 16) | \
                  (GPIOE_P11_CONF << 14) | (GPIOE_P11_MODE << 12) | \
                  (GPIOE_P10_CONF << 10) | (GPIOE_P10_MODE << 8) | \
                  (GPIOE_P09_CONF << 6) | (GPIOE_P09_MODE << 4) | \
                  (GPIOE_P08_CONF << 2) | (GPIOE_P08_MODE << 0)
